### ISSUE TITLE
企业宣传小程序

### ISSUE THREAD

**Issue by yaoshanliang** [opendigg/opending-share-projects#10]
项目名称：企业宣传小程序
子标题: 盛世华安小程序
相关介绍: 提供公司新闻资讯、产品服务、宣传视频、联系方式等
项目地址：[https://github.com/yaoshanliang/weapp-ssha](https://github.com/yaoshanliang/weapp-ssha)

**Comment by opendigg** [comment]
你好，这个小程序过于简单，opendigg暂时就不收录了，感谢你的关注。
