### ISSUE TITLE
提交项目：koahubjs

### ISSUE THREAD

**Issue by einsqing** [opendigg/opending-share-projects#11]
项目名称：[koahubjs](https://github.com/einsqing/koahubjs)
子标题: 基于 Koa.js 平台的 Node.js web 快速开发框架
相关介绍: KoaHub.js 是基于 Koa.js 平台的 Node.js web 快速开发框架。可以直接在项目里使用 ES6/7（Generator Function, Class, Async & Await）等特性，借助 Babel 编译，可稳定运行在 Node.js 环境上

**Comment by opendigg** [comment]
已收录：http://www.opendigg.com/p/koahubjs

**Comment by einsqing** [comment]
@opendigg 收录的使用说明是老版本的，新版本的使用说明有部分改动了，麻烦更新下。https://github.com/einsqing/koahubjs

**Comment by opendigg** [comment]
ok 更新完毕http://www.opendigg.com/p/koahubjs
