### ISSUE TITLE
react-native-smartbar

### ISSUE THREAD

**Issue by unix** [opendigg/opending-share-projects#13]
项目名称：react-native-smartbar
子标题： 更简单优雅的RN组件
相关介绍： 弥补了RN官方通用的tabbar组件，具备隐藏显示，指定路由跳转，图标与文字的自定义显示等API。目前已有多个项目使用在生产环境中，长期支持。
地址：https://github.com/WittBulter/react-native-smartbar

**Comment by opendigg** [comment]
已收录：http://www.opendigg.com/p/react-native-smartbar
