### ISSUE TITLE
sails-blog

### ISSUE THREAD

**Issue by unix** [opendigg/opending-share-projects#14]
项目名称：sails-blog
子标题： Angular4+Nodejs(Sails)开源博客
相关介绍： 简单、快速、优雅的单页面博客。完全前后端分离，使用新版Angular重新构建，通过标准的restful规范API交互。
预览：http://test.wittsay.cc/
后端地址：https://github.com/WittBulter/sails-blog
前端地址：https://github.com/WittBulter/sails-blog-frontend

**Comment by opendigg** [comment]
已收录：http://www.opendigg.com/p/sails-blog
