### ISSUE TITLE
FFToast

### ISSUE THREAD

**Issue by imlifengfeng** [opendigg/opending-share-projects#16]
项目名称：FFToast
子标题: GitHub中最强大的iOS Notification和AlertView框架，没有之一！
相关介绍: FFToast是一个非常强大的iOS message notifications和AlertView扩展。它可以很容易实现从屏幕顶部、屏幕底部和屏幕中间弹出一个通知。你可以很容易的自定义弹出的View.
GitHub链接：https://github.com/imlifengfeng/FFToast

**Comment by opendigg** [comment]
已收录：http://www.opendigg.com/p/FFToast
