### ISSUE TITLE
share

### ISSUE THREAD

**Issue by zhangking** [opendigg/opending-share-projects#17]
项目名称：N3-components
子标题: vue组件库 支持1和2
相关介绍: https://github.com/N3-components/N3-components

**Comment by bailicangdu** [comment]
项目名称：vue2-elm
子标题:  vue2 + vuex 构建的具有45个页面的大型单页面项目
相关介绍: 估计是目前最大的vue开源项目了

**Comment by opendigg** [comment]
已收录：http://www.opendigg.com/p/n3-components
