### ISSUE TITLE
分享一个vue项目

### ISSUE THREAD

**Issue by bailicangdu** [opendigg/opending-share-projects#18]
项目名称：vue2-elm
子标题: vue2 + vuex 构建的具有45个页面的大型单页面项目
相关介绍: 估计是目前最大的vue开源项目了
地址：https://github.com/bailicangdu/vue2-elm

**Comment by opendigg** [comment]
已收录并推荐至首页：http://www.opendigg.com/p/vue2-elm

**Comment by xiaobinwu** [comment]
mark
