### ISSUE TITLE
项目提交：Vue 地区选择器

### ISSUE THREAD

**Issue by savokiss** [opendigg/opending-share-projects#19]
项目名称：[vue-cascading-address](https://github.com/savokiss/vue-cascading-address)
子标题: Vue 地区选择器
相关介绍: 基于VueJS的简单地址选择器
DEMO: [vue-cascading-address](http://savokiss.me/vue-cascading-address/)

**Comment by opendigg** [comment]
已收录：http://www.opendigg.com/p/vue-cascading-address
