### ISSUE TITLE
ILayoutAnimationController

### ISSUE THREAD

**Issue by HuanHaiLiuXin** [opendigg/opending-share-projects#22]
项目名称：ILayoutAnimationController
子标题: 自定义LayoutAnimationController
相关介绍: 自定义LayoutAnimationController，可任意定制ViewGroup实例内部子View的动画执行顺序，1行代码就让你的ViewGroup拥有华丽的布局动画！

项目地址：https://github.com/HuanHaiLiuXin/ILayoutAnimationController

**Comment by opendigg** [comment]
已收录:http://www.opendigg.com/p/ILayoutAnimationController

**Comment by opendigg** [comment]
已收录:http://www.opendigg.com/p/ILayoutAnimationController
