### ISSUE TITLE
vue-event-calendar

### ISSUE THREAD

**Issue by GeoffZhu** [opendigg/opending-share-projects#23]
项目名称：vue-event-calendar
子标题: vue2事件日历组件
相关介绍: vue-event-calendar是一款简单小巧的事件日历组件，针对Vue2开发。样式美观，且响应式。

项目地址：https://github.com/GeoffZhu/vue-event-calendar

**Comment by opendigg** [comment]
已收录：http://www.opendigg.com/p/vue-event-calendar
