### ISSUE TITLE
EFQRCode

### ISSUE THREAD

**Issue by EyreFree** [opendigg/opending-share-projects#28]
花式二维码生成库信息麻烦更新一下，之前抓取的 1.0.0 版本的信息，太旧了，谢谢，🙏...

---

项目名称：
EFQRCode

二级标题：
A better way to operate two-dimensional code in Swift.

相关介绍：
EFQRCode 是一个用 Swift 编写的用来生成和识别二维码的库，它基于系统二维码生成与识别进行开发。
生成：利用输入的水印图/图标等资源生成各种艺术二维码；
识别：识别率比 iOS 原生二维码识别率更高。

项目地址：
https://github.com/EyreFree/EFQRCode

**Comment by opendigg** [comment]
已收录：http://www.opendigg.com/p/EFQRCode

**Comment by EyreFree** [comment]
之前抓取的 1.0.0 版本的信息，太旧了，能否更新一下，感谢，🙏
