### ISSUE TITLE
LivelyGIFs

### ISSUE THREAD

**Issue by KrisYu** [opendigg/opending-share-projects#29]
项目名称：LivelyGIFs
子标题: LivelyGIFs
相关介绍: 把live photo变成gif的一个iOS App, 逻辑简单，初学者友好

**Comment by opendigg** [comment]
项目地址：https://github.com/KrisYu/LivelyGIFs

**Comment by opendigg** [comment]
已收录：http://www.opendigg.com/p/livelygifs
