### ISSUE TITLE
Vue router storage

### ISSUE THREAD

**Issue by ElderJames** [opendigg/opending-share-projects#30]
项目名称：[vue-router-storage](https://github.com/ElderJames/vue-router-storage)
子标题: 一个Vue历史路由持久化的解决方案。
相关介绍: 
Vue中使用HTML5 history历史模式时，能通过浏览器进行前进后退操作。但是，当在地址栏直接填写多级路由地址或者从外部链接跳转到Vue应用的多级路由时，会造成历史记录丢失、无法回退上级页面的尴尬情况。本方案则为vue提供历史记录重构和持久化的功能，解决历史记录丢失和无法回退的问题。

**Comment by havenxie** [comment]
[项目名称：](https://github.com/havenxie/weapp-sportsnews)
子标题: 微信小程序 Sports News(体育新闻)
相关介绍:
小程序提供最新的、最具关注度、最具爆炸性的体育界新闻。
app由主页、专题页、文章页、图片页、视屏页等页面构成。主页呈现实时的新闻资讯，专题页呈现特定类别的讯息，文章页展示最具代表性的犀利文章，图片和视频页展示高清大图和相关video。

**Comment by opendigg** [comment]
已收录：http://www.opendigg.com/p/vue-router-storage

**Comment by ElderJames** [comment]
谢谢
