### ISSUE TITLE
微信小程序 Sports News(体育新闻)

### ISSUE THREAD

**Issue by havenxie** [opendigg/opending-share-projects#31]
项目名称：[weapp-sportsnews](https://github.com/havenxie/weapp-sportsnews)
子标题: 微信小程序 Sports News(体育新闻)
相关介绍:
小程序提供最新的、最具关注度、最具爆炸性的体育界新闻。
app由主页、专题页、文章页、图片页、视屏页等页面构成。主页呈现实时的新闻资讯，专题页呈现特定类别的讯息，文章页展示最具代表性的犀利文章，图片和视频页展示高清大图和相关video。

**Comment by opendigg** [comment]
已收录：http://www.opendigg.com/p/weapp-sportsnews
