### ISSUE TITLE
Excelize

### ISSUE THREAD

**Issue by xuri** [opendigg/opending-share-projects#37]
项目名称: Excelize
子标题: Go 语言读写 Excel 文档类库
相关介绍: 基于微软的 Office OpenXML 标准，支持创建图表、插入图片等复杂功能的 Excel 类库
项目地址: [github.com/Luxurioust/excelize](https://github.com/Luxurioust/excelize)

**Comment by opendigg** [comment]
http://www.opendigg.com/p/excelize
