### ISSUE TITLE
提交项目

### ISSUE THREAD

**Issue by codeestX** [opendigg/opending-share-projects#4]
项目名称：[GeekNews](https://github.com/codeestX/GeekNews)
子标题：A pure reading App for you
相关介绍：面向极客/程序员的阅读应用

项目名称：[ENViews](https://github.com/codeestX/ENViews)
子标题：A cool dynamic view library
相关介绍：Android动效控件库

**Comment by opendigg** [comment]
已收录：
http://www.opendigg.com/p/geeknews 
http://www.opendigg.com/p/ENViews
