### ISSUE TITLE
TLRLoadRefresh(下拉刷新和上拉加载)

### ISSUE THREAD

**Issue by borneywpf** [opendigg/opending-share-projects#40]
项目名称：TLRLoadRefresh
项目地址：https://github.com/borneywpf/TLRLoadRefresh
子标题: 非常实用的下拉刷新和上拉加载控件 TLRLoadRefresh
相关介绍: TLRLoadRefresh是一个支持ListView,RecycleView,ViewGroup等多种view下拉刷新和上拉加载的UI组件,使用具有很大的灵活性。可以根据自己的不同需求来定义不同UI设计，可以灵活的自定义下拉刷新的Head和上拉加载的Foot

**Comment by opendigg** [comment]
http://www.opendigg.com/p/tlrloadrefresh

**Comment by borneywpf** [comment]
3q
