### ISSUE TITLE
提交 Coding WebIDE

### ISSUE THREAD

**Issue by tvvocold** [opendigg/opending-share-projects#5]
项目名称：Coding WebIDE

子标题: Coding WebIDE(https://ide.coding.net) 是 Coding 自主研发的在线集成开发环境 (IDE)。用户可以通过 WebIDE 创建项目的工作空间, 进行在线开发, 调试等操作。同时 WebIDE 集成了 Git 代码版本控制, 用户可以选择 Coding、GitHub、BitBucket、GitLab 等任意的代码仓库。 WebIDE 还提供了分享开发环境的功能, 用户可以保存当前的开发环境, 分享给团队的其他成员。

相关介绍: https://ide.coding.net/community

**Comment by opendigg** [comment]
你好，目前opendigg只能收录GitHub的项目。

**Comment by tvvocold** [comment]
@opendigg 也可以，https://github.com/Coding/WebIDE  另外 https://github.com/coding 这里也有一些可以收录哈；）

**Comment by opendigg** [comment]
你好，收录如下
Coding-Android:http://www.opendigg.com/p/coding-android
Coding-iOS:http://www.opendigg.com/p/coding-ios
Coding-iPad:http://www.opendigg.com/p/coding-ipad
Coding WebIDE:http://www.opendigg.com/p/webide-coding
